server:
  port: 8080

spring:
  datasource:
    username: root
    password: 159357
    #url中database为对应的数据库名称
    #url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/capfdemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.capf.af.bootdemo.entity

#showSql
logging:
  level:
    com.capf.af.bootdemo.mapper: debug
   # com.example.demo.mapper: debug